### ISSUE TITLE
GooglePlus.bundle of SDK 1.7.1 not loaded

### ISSUE THREAD

**Issue by priore** [adamotte/googleplus-ios-sdk#4]
When i use the GTMOAuth2ViewControllerTouch the nib not loaded correctly from GooglePlus.bundle, while if I put the xib it all works fine.

note: the bundle is correctly included in the target

Help please.

**Comment by adamotte** [comment]
Hi @priore , thanks for opening this issue. I'm sorry that i've not the time right now to check it out.
The implementation for authNibName is
```objective-c
+ (NSString *)authNibName {
  // subclasses may override this to specify a custom nib name
  return @"GTMOAuth2ViewTouch";
}
```
Maybe your issue is there ?

**Comment by priore** [comment]
Sorry, but this solution, with GTMOAuth2ViewTouch or GPPOAuth2ViewTouch (included in bundle), not work.
